---
build_from:
  aarch64: 'ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.17'
  armhf: 'ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.17'
  armv7: 'ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.17'
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: Red Reactor Monitor'
  org.opencontainers.image.description: 'Red Reactor Battery Monitoring service.'
  org.opencontainers.image.source: 'https://github.com/mreditor97/homeassistant-addons'
  org.opencontainers.image.licenses: 'MIT'
